### ISSUE TITLE
Format error with `rucio download`

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#2362]
Motivation
----------

```
# rucio --version 
rucio 1.19.4
# rucio download   "238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar"
2019-03-21 13:58:45,998    INFO    Processing 1 item(s) for input
2019-03-21 13:58:45,998    INFO    Getting sources of DIDs
2019-03-21 13:58:46,434    ERROR    %d format: a number is required, not NoneType
```

**Comment by TWAtGH** [comment]
```
(.venv) [13:49][twegner@twegner-dev rucio]$ rucio download "238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar"
2019-03-25 13:50:19,406	INFO	Processing 1 item(s) for input
2019-03-25 13:50:19,406	INFO	Getting sources of DIDs
2019-03-25 13:50:20,992	INFO	Using main thread to download 0 file(s)
2019-03-25 13:50:20,993	ERROR	None of the requested files have been downloaded.
```
could you please give debug output?

**Comment by vingar** [comment]
```
# rucio -v  download  "238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar"  --rse EISCAT 
2019-03-25 12:56:10,672	INFO	Processing 1 item(s) for input
2019-03-25 12:56:10,673	DEBUG	num_unmerged_items=1; num_dids=1; num_merged_items=1
2019-03-25 12:56:10,673	INFO	Getting sources of DIDs
2019-03-25 12:56:10,673	DEBUG	schemes: ['davs', 'gsiftp', 'https', 'root', 'srm', 'file']
2019-03-25 12:56:10,673	DEBUG	rse_expression: (EISCAT)\istape=true
2019-03-25 12:56:10,673	DEBUG	num DIDs for list_replicas call: 1
2019-03-25 12:56:10,942	DEBUG	num resolved files: 1
2019-03-25 12:56:10,949	DEBUG	"unzip -v" returned with exitcode 127
2019-03-25 12:56:10,954	DEBUG	"tar --version" returned with exitcode 0
2019-03-25 12:56:10,954	DEBUG	num list_replicas calls: 1
2019-03-25 12:56:10,954	DEBUG	Queueing file: 238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar
2019-03-25 12:56:10,955	DEBUG	real parents: set([])
2019-03-25 12:56:10,955	DEBUG	options: {'238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar': {'ignore_checksum': False, 'transfer_timeout': 3600, 'destinations': set([('.', False)])}}
2019-03-25 12:56:10,955	DEBUG	Prepared sources: num_sources=0/0; num_non_cea_sources=0; num_cea_ids=0
2019-03-25 12:56:10,956	ERROR	%d format: a number is required, not NoneType
2019-03-25 12:56:10,956	DEBUG	This means the parameter you passed has a wrong type.
Completed in 0.2852 sec.
```

**Comment by TWAtGH** [comment]
Thanks. The commit should fix it. Difficult to test though.

**Comment by vingar** [comment]
It fixes the error message but it still doesn't download the file. It's a regression as a previous `rucio download `version can download the file, e.g., `1.17.8`.

**Comment by TWAtGH** [comment]
That's correct. It cannot be downloaded because there are no PFNs. I thought this is maybe expected.
Could you show me a `list-file-replicas --metalink` please?

**Comment by vingar** [comment]
```
bash-4.2# rucio list-file-replicas --metalink  "238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar" 
<?xml version="1.0" encoding="UTF-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
 <file name="manda4_cp1_3.00u_SW20140322.part1.tar">
  <identity>238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar</identity>
  <hash type="adler32">d9901472</hash>
  <size>1954140160</size>
  <glfn name="/eiscat3d/rucio/238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar"></glfn>
  <url location="NDGF" domain="wan" priority="1" client_extract="false">gsiftp://preprod-srm.ndgf.org:2811/eiscat3d/rucio/238357;238356;238359/e6/19/manda4_cp1_3.00u_SW20140322.part1.tar</url>
  <url location="NDGF" domain="wan" priority="2" client_extract="false">https://preprod-srm.ndgf.org:443/eiscat3d/rucio/238357;238356;238359/e6/19/manda4_cp1_3.00u_SW20140322.part1.tar</url>
 </file>
</metalink>
```

**Comment by TWAtGH** [comment]
Thanks. For the download you used `--rse EISCAT` but these rerplicas are on 'NDGF'.

**Comment by vingar** [comment]
Nope, one replica is on EISCAT:
```
# rucio list-file-replicas   "238357;238356;238359:manda4_cp1_3.00u_SW20140322.part1.tar" 
+----------------------+---------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------+
| SCOPE                | NAME                                  | FILESIZE   | ADLER32   | RSE: REPLICA                                                                                                             |
|----------------------+---------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------|
| 238357;238356;238359 | manda4_cp1_3.00u_SW20140322.part1.tar | 1.954 GB   | d9901472  | EISCAT: http://www.eiscat.se:37008/238357;238356;238359/manda4_cp1_3.00u_SW20140322.part1.tar                            |
| 238357;238356;238359 | manda4_cp1_3.00u_SW20140322.part1.tar | 1.954 GB   | d9901472  | NDGF: gsiftp://preprod-srm.ndgf.org:2811/eiscat3d/rucio/238357;238356;238359/e6/19/manda4_cp1_3.00u_SW20140322.part1.tar |
+----------------------+---------------------------------------+------------+-----------+--------------------------------------------------------------------------------------------------------------------------+
```
