### ISSUE TITLE
Rich CLI cannot display RSE information for some RSEs

### ISSUE THREAD

**Issue by bjwhite-fnal** [rucio/rucio#7693]
### Description

Using the Rich CLI in rucio-clients==37.2.0, some RSEs show an error when trying to display their settings. The server does return the requested RSE information to the client properly, there is just a client-side error in parsing it.

```
$ rucio rse show INFN_CNAF_TAPE
⣽ Fetching RSE info2025-05-01 09:39:15,937      ERROR   unhashable type: 'dict'
```

I've found the common theme to be tape sites that have the SRM protocol configured. If I turn off the Rich CLI and inspect these RSEs, the extended attributes show up as a dictionary and not JSON, which I suspect is the problem here.

```
$ rucio rse show INFN_CNAF_TAPE
<removed>
Protocols:
==========
  srm
    domains: '{"lan": {"read": 1, "write": 1, "delete": 1}, "wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy_read": 1, "third_party_copy_write": 1}}'
    extended_attributes: {'space_token': '<redacted>', 'web_service_path': '/srm/managerv2?SFN='}
    hostname: storm-fe-archive.cr.cnaf.infn.it
    impl: rucio.rse.protocols.gfal.Default
    port: 8444
    prefix: /icarus
    scheme: srm
<more removed>
```

### Steps to reproduce

1. Have an RSE with extended attributes for a protocol configured
2. Try `rucio rse show <rse>`

### Rucio Version

Client: 37.2.0, Server 37.2.0

**Comment by voetberg** [comment]
I think this was fixed at some point silently - 

Example: 

```
> rucio config add --section experimental --key cli --value rich
> rucio rse show <rse with extended protocol info> 
...
Protocols:
  file
  ┌─────────────────────┬───────────────────────────────────┐
  │ domains             │                                   │
  │                     │ ├── lan                           │
  │                     │ │   ├── read: 1                   │
  │                     │ │   ├── write: 1                  │
  │                     │ │   └── delete: 1                 │
  │                     │ └── wan                           │
  │                     │     ├── read: 1                   │
  │                     │     ├── write: 1                  │
  │                     │     ├── delete: 1                 │
  │                     │     ├── third_party_copy_read: 0  │
  │                     │     └── third_party_copy_write: 0 │
  │ extended_attributes │                                   │
  │ hostname            │ localhost                         │
  │ impl                │ rucio.rse.protocols.posix.Default │
  │ port                │ 0                                 │
  │ prefix              │ /tmp/rucio_rse/                   │
  │ scheme              │ file                              │
  └─────────────────────┴───────────────────────────────────┘
...
```

I can add an additional test to make sure this stays correct but @rdimaio or @d-ylee can you check this on a live deployment?

**Comment by d-ylee** [comment]
Hi @voetberg I'm still getting the same error. I updated our deployment to 38.1.0 and also upgraded the client to 38.1.0. I believe it is for the extended attributes, since the SRM protocol needs the space_token and web_service_path.

**Comment by voetberg** [comment]
Thanks for checking @d-ylee 

For posterity: 
This was a nasty combo of my inability to read (I totally missed it was *just* the extended attributes) and the testing config mockup not working as intended (See the comment on the linked PR)
